#################################################
# DO Community Playbooks: apache
#################################################
---
- hosts: do_clusterservers
  become: true
#  vars_files:
#    - vars/default.yml
  roles:
    - docker