version: '3.7'
services:
  prometheus:
    network_mode: host
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
#    networks:
#      - inbound
    labels:
      service.port: '9090'
      service.name: prometheus


  slickdeals-grafana:
    image: grafana/grafana
    network_mode: host
    container_name: slickdeals-grafana
    ports:
      - "3000:3000"
#    networks:
#      - inbound
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      - GF_SMTP_HOST=smtpout.secureserver.net:465
      - GF_SMTP_USER=chet@pressler.com
      - GF_SMTP_PASSWORD=utaee85
      - GF_SMTP_ENABLED=true
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=admin@ci.loyalty.slickdeals.net
      - GF_SMTP_FROM_NAME=grafana admin
      - GF_SERVER_DOMAIN=grafana.ci.loyalty.slickdeals.net
      - GF_SERVER_ROOT_URL=https://grafana
    labels:
      - "SERVICE_NAME=slickdeals-grafana"
      - "service.port=3000"
      - "service.name=slickdeals-grafana"
      - "service.proxy=http"


  zipkin:
    network_mode: host
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
#    networks:
#      - inbound
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://localhost:9200
      - ES_DATE_SEPARATOR=
    labels:
      service.port: '9411'
      service.name: zipkin
      service.proxy: http

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/var/lib/elasticsearch
      - ${PWD}/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    labels:
      service.port: '9200'
      service.name: elasticsearch
      service.proxy: http
#    networks:
#      - inbound
  kibana:
    network_mode: host
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://localhost:9200
    labels:
      service.port: '5601'
      service.name: kibana
      service.proxy: http
#    networks:
#      - inbound

networks:
  inbound:
    name: inbound

volumes:
  prometheus_data: {}
  grafana_data: {}
  elasticsearch_data: {}
