#################################################
# DO Community Playbooks: apache
#################################################
---
- hosts: chefserver
  become: true
  vars_files:
    - vars/default.yml
  roles:
    - chef