#################################################
# DO Community Playbooks: apache
#################################################
---
- hosts: dnsservers
  become: true
  vars_files:
    - vars/default.yml
  roles:
    - ansible-role-bind-master